# Generated by Django 6.0.5 on 2026-06-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestEnviroments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('test_store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teststore')),
            ],
        ),
        migrations.CreateModel(
            name='TestValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_tp', models.CharField(max_length=100)),
                ('suc_tp', models.CharField(max_length=100)),
                ('eva_tp', models.CharField(max_length=100)),
                ('deg_tp', models.CharField(max_length=100)),
                ('def_status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('test_enviroments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testenviroments')),
            ],
        ),
    ]
