# Generated by Django 6.0.5 on 2026-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testvalues',
            index=models.Index(fields=['test_enviroments_id_id', 'date'], name='idx_envid_date'),
        ),
    ]
