# Generated by Django 6.0.5 on 2026-06-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvalues',
            name='deg_tp',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='testvalues',
            name='env_tp',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='testvalues',
            name='eva_tp',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='testvalues',
            name='suc_tp',
            field=models.CharField(),
        ),
    ]
