# Generated by Django 6.0.5 on 2026-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testvalues_idx_envid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvalues',
            name='deg_tp',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='testvalues',
            name='env_tp',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='testvalues',
            name='eva_tp',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='testvalues',
            name='suc_tp',
            field=models.FloatField(blank=True),
        ),
    ]
